### PR TITLE
[INJI-69]fix:The mobile camera is not opening on the scan page when the flight mode is turned

### PR DESCRIPTION
**Pull request by srikanth716**
fix:The mobile camera is not opening on the scan page when the flight mode is turned

### CODE REVIEW

**Review by vharsh — COMMENTED** [review]
Minor changes suggested based on access permissions for native platforms.

**Comment by vharsh** [comment]
This is on hold because it inadvertently uses the larger dependency(50kB vs 500kB) and might have an impact on increased APK/IPA sizes. Please share more pointers on this @Alka1703

**Comment by Alka1703** [comment]
Have shared the apk size concern with Srikanth and have also asked him to look into other similar libraries. Also, there are some feedbacks on the logic implementation as well which I have shared with Srikanth.

**Comment by srikanth716** [comment]
We can close this PR since it is raised from my local repo. I have raised another [PR](https://github.com/tw-mosip/inji/pull/97) for the same from tw-mosip directly

**Comment by srikanth716** [comment]
We can close this PR since it is raised from my local repo. I have raised another [PR](https://github.com/tw-mosip/inji/pull/97) for the same from tw-mosip directly

**Pull request closed without merging**
